### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by wangtao1996study** [mattpfr/lmanet#5]
Excuse me.When i run the code,there is an error:

Traceback (most recent call last):
  File "main.py", line 156, in <module>
    main(args)
  File "main.py", line 61, in main
    mp.spawn(process, nprocs=args.gpus, args=(args, ))
  File "/root/anaconda3/envs/LMAnet/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/anaconda3/envs/LMAnet/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/root/anaconda3/envs/LMAnet/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/root/anaconda3/envs/LMAnet/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/data/user/wangtao/anaconda_inatall/envs/lmanet-main/main.py", line 45, in process
    model = load_model_from_file(args, model_path, board, gpu, checkpoint)
  File "/data/user/wangtao/anaconda_inatall/envs/lmanet-main/utils/loading.py", line 116, in load_model_from_file
    weights_dict = torch.load(weights_path, map_location=lambda storage, loc: storage)
  File "/root/anaconda3/envs/LMAnet/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/anaconda3/envs/LMAnet/lib/python3.8/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x0a'.

Can you help me please?

**Comment by mattpfr** [comment]
Hi @wangtao1996study, it seems that this error point at something going wrong when loading the model. Maybe somehow the weights that you are trying to load got corrupted for some reason ? Could you tell me the command that you are trying to run ?
